const data = {
products: [
    {
      _id: '1',
      name: 'Slim Shirt',
      category: 'Shirt',
      image: '/images/p1.jpg',
      price: 120,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',  
    },
    {
        _id: '2',
        name: 'Slim Shirt',
        category: 'Shirt',
        image: '/images/p2.jpg',
        price: 120,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'High quality product',  
      },
      {
        _id: '3',
        name: 'Slim Jeans',
        category: 'Jeans',
        image: '/images/p3.jpg',
        price: 110,
        brand: 'Lee',
        rating: 4.5,
        numReviews: 10,
        description: 'High quality product',  
      },
      {
        _id: '4',
        name: 'Slim T-shirt',
        category: 'T-Shirt',
        image: '/images/p4.jpg',
        price: 120,
        brand: 'Lacoste',
        rating: 4.5,
        numReviews: 10,
        description: 'High quality product',  
      },
      {
        _id: '5',
        name: 'Slim Pants',
        category: 'Pants',
        image: '/images/p5.jpg',
        price: 90,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 10,
        description: 'High quality product',  
      },
      {
        _id: '6',
        name: 'Slim Shirt',
        category: 'Shirt',
        image: '/images/p6.jpg',
        price: 100,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'High quality product',  
      },
]}

export default data;